apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: {{ .Values.app1.replicas }}
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      nodeSelector:
        {{- toYaml .Values.app1.nodeLabels | nindent 8 }}
      containers:
        - name: app1
          image: {{ .Values.app1.image }}