apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: {{ .Values.app2.replicas }}
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      nodeSelector:
        {{- toYaml .Values.app2.nodeLabels | nindent 8 }}
      containers:
        - name: app2
          image: {{ .Values.app2.image }}